---
- name: Descarca repo-ul direct pe router fara Python
  hosts: all
  gather_facts: no

  tasks:
    - name: Creeaza folderul pe router
      raw: mkdir -p /tmp/fisierele_mele

    - name: Afiseaza un mesaj ca s-a conectat cu succes
      raw: echo "Conexiune reusita pe RUT906!" > /tmp/fisierele_mele/status.txt
