---
- name: Descarca fisierele pe router
  hosts: all
  gather_facts: no

  tasks:
    - name: Creeaza folderul dorit
      raw: mkdir -p /root/teste

    - name: Descarca fisierul direct in folderul nou
      raw: wget -O /root/teste/README.md https://raw.githubusercontent.com/Ganea-Teodor/Hello-world-/main/README.md
